# Generated by Django 2.2.3 on 2020-10-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_pokemon_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_evolution', to='pokemon_entities.Pokemon'),
        ),
    ]
