# Generated by Django 2.2.3 on 2020-10-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_pokemon_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='child',
        ),
    ]
