# Generated by Django 2.2.3 on 2020-10-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_remove_pokemon_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='parent',
            new_name='evolution',
        ),
    ]
